// <auto-generated />
namespace TBT_Blog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tblPostsACPostNameForNavigation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tblPostsACPostNameForNavigation));
        
        string IMigrationMetadata.Id
        {
            get { return "201801131428131_tblPosts-AC-PostNameForNavigation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
